### ISSUE TITLE
multiple page long text rewriting

### ISSUE THREAD

**Issue by futurist** [sindresorhus/log-update#10]
When output long text(e.g. 100 lines spins)  where as the terminal rows is 30 lines, how to make it overwrite the  previous page that already exceed the screen?

The needed result is over write(refresh) the whole 100 lines, without _leaking_ lines.

**Comment by SamVerschueren** [comment]
I looked into this and it looks like it's just not possible. Under the hood, `log-update` uses [`ansi-escapes`](https://github.com/sindresorhus/ansi-escapes) and more specifically, [`.eraseLines()`](https://github.com/sindresorhus/ansi-escapes#eraselinescount). It looks like terminals don't allow you to clear lines which are outside the viewport.

@sindresorhus @Qix- Any ideas? Currently it seems like this is not possible because terminals don't allow it.

**Comment by sindresorhus** [comment]
We can only manipulate the visible viewport.

**Comment by SamVerschueren** [comment]
Then this "issue" is just unfixable.

**Comment by astoilkov** [comment]
Have you looked into [draftlog](https://github.com/ivanseidel/node-draftlog)? I think they cache the non visible lines and when they come into view they update them.

**Comment by Qix-** [comment]
When consoles have "scrollback", it's really your terminal emulator (or screen, or tmux, etc.) buffering those lines.

@sindresorhus is correct when he says you can only manipulate the visible viewport.

Most libraries that do more complex terminal manipulation, such as (n)curses or the various termcap libraries do all sorts of buffering for you.
