### ISSUE TITLE
Leading spaces are removed from output

### ISSUE THREAD

**Issue by uschek** [sindresorhus/log-update#20]
**example.js**:

```js
'use strict';
const logUpdate = require('log-update');

const frames = ['-', '\\', '|', '/'];
let i = 0;

setInterval(() => {
	const frame = frames[i = ++i % frames.length];

	logUpdate(
`
        ♥♥
   ${frame} unicorns ${frame}
        ♥♥
`
	);
}, 80);
```

![log-update](https://cloud.githubusercontent.com/assets/2123235/25350310/fcf72910-2924-11e7-94a6-76c56a5fc635.gif)

This was probably introduced by d0ca53ec0f2ed88b18f910227eca0964738947c8.

**Comment by SamVerschueren** [comment]
Yes it seems to be a problem with `wrap-ansi`. Going to look into it.

**Comment by SamVerschueren** [comment]
It's because of [this](https://github.com/chalk/wrap-ansi/blob/master/index.js#L110) check. Splitting the above in words [here](https://github.com/chalk/wrap-ansi/blob/master/index.js#L104) results in

```
[ '' ]
[ '', '', '', '', '', '', '', '', '♥♥' ]
[ '', '', '', '\\', 'unicorns', '\\' ]
[ '', '', '', '', '', '', '', '', '♥♥' ]
[ '' ]
[ '' ]
```

So the [check](https://github.com/chalk/wrap-ansi/blob/master/index.js#L110) that I linked above does not add a space in case the length of the word is 0. So let me dive deeper why that check is necessary.

**Comment by donaldpipowitch** [comment]
> So let me dive deeper why that check is necessary.

Do you know why this is necessary? I just faced this bug, too.
