### ISSUE TITLE
Update only the changed lines

### ISSUE THREAD

**Issue by zkochan** [sindresorhus/log-update#25]
Hi! Awesome project, thanks for it!

I use this package for the default [pnpm reporter](https://github.com/pnpm/pnpm-default-reporter). It works fine but when the updated text is big there is a noticeable flickering (in Windows [cmder](http://cmder.net/)). Would it be possible to make `log-update` smarter and instead of rewriting everything, do some diffing and update only the changed parts of the console view?

**Comment by sindresorhus** [comment]
I wouldn't just assume that will be faster. My theory is that it will be slower as it will require more draw calls which comes with an overhead. I have no proof either way though. It might also introduce bugs as not all terminals behave the same way when doing cursor manipulations. I've been using this module in lots of projects for years and have never experienced any flickering.

I might be worth looking for a different module since I personally don't care about performance in terminals on Windows. If you can show performance issues on Linux or macOS terminals, I'll take another look.

**Comment by zkochan** [comment]
I haven't noticed issues on other systems, so I close it.
